export type Language = 'en' | 'sw';

export type TranslationKey = keyof typeof translations.en;

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    inventory: 'Inventory',
    suppliers: 'Suppliers',
    orders: 'Orders',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    
    // Dashboard
    totalProducts: 'Total Products',
    lowStockItems: 'Low Stock Items',
    expiringSoon: 'Expiring Soon',
    todaySales: "Today's Sales",
    todayRevenue: "Today's Revenue",
    stockLevels: 'Stock Levels',
    recentSales: 'Recent Sales',
    quickActions: 'Quick Actions',
    
    // Alerts
    lowStockAlert: 'Low Stock Alert',
    expiryAlert: 'Expiry Alert',
    autoOrderGenerated: 'Auto Order Generated',
    
    // Products
    products: 'Products',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productName: 'Product Name',
    productNameSwahili: 'Product Name (Swahili)',
    category: 'Category',
    sku: 'SKU',
    quantity: 'Quantity',
    minStockLevel: 'Minimum Stock Level',
    buyingPrice: 'Buying Price',
    sellingPrice: 'Selling Price',
    expiryDate: 'Expiry Date',
    batchNumber: 'Batch Number',
    supplier: 'Supplier',
    
    // Categories
    seeds: 'Seeds',
    fertilizers: 'Fertilizers',
    pesticides: 'Pesticides',
    veterinary: 'Veterinary',
    tools: 'Tools',
    allCategories: 'All Categories',
    
    // POS
    searchProducts: 'Search products...',
    cart: 'Cart',
    emptyCart: 'Cart is empty',
    subtotal: 'Subtotal',
    total: 'Total',
    clearCart: 'Clear Cart',
    checkout: 'Checkout',
    payment: 'Payment',
    cash: 'Cash',
    mpesa: 'M-Pesa',
    customerPhone: 'Customer Phone',
    processPayment: 'Process Payment',
    paymentSuccessful: 'Payment Successful',
    receipt: 'Receipt',
    printReceipt: 'Print Receipt',
    newSale: 'New Sale',
    
    // M-Pesa
    mpesaPayment: 'M-Pesa Payment',
    enterPhoneNumber: 'Enter phone number',
    sendingRequest: 'Sending STK Push...',
    waitingConfirmation: 'Waiting for confirmation...',
    paymentConfirmed: 'Payment Confirmed',
    transactionRef: 'Transaction Ref',
    
    // Suppliers
    addSupplier: 'Add Supplier',
    editSupplier: 'Edit Supplier',
    deleteSupplier: 'Delete Supplier',
    supplierName: 'Supplier Name',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    trustedSupplier: 'Trusted Supplier',
    autoOrder: 'Auto Order',
    enableAutoOrder: 'Enable Auto Order',
    
    // Orders
    purchaseOrders: 'Purchase Orders',
    createOrder: 'Create Order',
    orderStatus: 'Order Status',
    pending: 'Pending',
    ordered: 'Ordered',
    received: 'Received',
    cancelled: 'Cancelled',
    autoGenerated: 'Auto Generated',
    confirmOrder: 'Confirm Order',
    markReceived: 'Mark as Received',
    cancelOrder: 'Cancel Order',
    
    // Reports
    salesReport: 'Sales Report',
    inventoryReport: 'Inventory Report',
    expiryReport: 'Expiry Report',
    exportReport: 'Export Report',
    dateRange: 'Date Range',
    from: 'From',
    to: 'To',
    generateReport: 'Generate Report',
    
    // Settings
    language: 'Language',
    english: 'English',
    swahili: 'Kiswahili',
    notifications: 'Notifications',
    lowStockThreshold: 'Low Stock Threshold',
    expiryWarningDays: 'Expiry Warning Days',
    saveSettings: 'Save Settings',
    backupData: 'Backup Data',
    restoreData: 'Restore Data',
    
    // Auth
    login: 'Login',
    username: 'Username',
    password: 'Password',
    loginError: 'Invalid username or password',
    sessionExpired: 'Session expired. Please login again.',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    noResults: 'No results found',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    confirm: 'Confirm',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    price: 'Price',
    unit: 'Unit',
    items: 'items',
    ksh: 'KSh',
    
    // Welcome
    welcomeBack: 'Welcome back',
    agrovetSystem: 'Agrovet Management System',
  },
  sw: {
    // Navigation
    dashboard: 'Dashibodi',
    pos: 'Mahali pa Mauzo',
    inventory: 'Hesabu ya Bidhaa',
    suppliers: 'Wasambazaji',
    orders: 'Maagizo',
    reports: 'Ripoti',
    settings: 'Mipangilio',
    logout: 'Toka',
    
    // Dashboard
    totalProducts: 'Jumla ya Bidhaa',
    lowStockItems: 'Bidhaa Chache',
    expiringSoon: 'Zinazoisha Hivi Karibuni',
    todaySales: 'Mauzo ya Leo',
    todayRevenue: 'Mapato ya Leo',
    stockLevels: 'Viwango vya Bidhaa',
    recentSales: 'Mauzo ya Hivi Karibuni',
    quickActions: 'Vitendo vya Haraka',
    
    // Alerts
    lowStockAlert: 'Tahadhari ya Bidhaa Chache',
    expiryAlert: 'Tahadhari ya Kuisha',
    autoOrderGenerated: 'Agizo la Kiotomatiki Limeundwa',
    
    // Products
    products: 'Bidhaa',
    addProduct: 'Ongeza Bidhaa',
    editProduct: 'Hariri Bidhaa',
    deleteProduct: 'Futa Bidhaa',
    productName: 'Jina la Bidhaa',
    productNameSwahili: 'Jina la Bidhaa (Kiswahili)',
    category: 'Aina',
    sku: 'Nambari ya Bidhaa',
    quantity: 'Kiasi',
    minStockLevel: 'Kiwango cha Chini',
    buyingPrice: 'Bei ya Kununua',
    sellingPrice: 'Bei ya Kuuza',
    expiryDate: 'Tarehe ya Kuisha',
    batchNumber: 'Nambari ya Kundi',
    supplier: 'Msambazaji',
    
    // Categories
    seeds: 'Mbegu',
    fertilizers: 'Mbolea',
    pesticides: 'Dawa za Wadudu',
    veterinary: 'Dawa za Mifugo',
    tools: 'Zana',
    allCategories: 'Aina Zote',
    
    // POS
    searchProducts: 'Tafuta bidhaa...',
    cart: 'Kikapu',
    emptyCart: 'Kikapu ni tupu',
    subtotal: 'Jumla ndogo',
    total: 'Jumla',
    clearCart: 'Futa Kikapu',
    checkout: 'Lipia',
    payment: 'Malipo',
    cash: 'Taslimu',
    mpesa: 'M-Pesa',
    customerPhone: 'Simu ya Mteja',
    processPayment: 'Fanya Malipo',
    paymentSuccessful: 'Malipo Yamefanikiwa',
    receipt: 'Risiti',
    printReceipt: 'Chapisha Risiti',
    newSale: 'Mauzo Mapya',
    
    // M-Pesa
    mpesaPayment: 'Malipo ya M-Pesa',
    enterPhoneNumber: 'Ingiza nambari ya simu',
    sendingRequest: 'Inatuma ombi la STK...',
    waitingConfirmation: 'Inasubiri uthibitisho...',
    paymentConfirmed: 'Malipo Yamethibitishwa',
    transactionRef: 'Nambari ya Muamala',
    
    // Suppliers
    addSupplier: 'Ongeza Msambazaji',
    editSupplier: 'Hariri Msambazaji',
    deleteSupplier: 'Futa Msambazaji',
    supplierName: 'Jina la Msambazaji',
    phone: 'Simu',
    email: 'Barua Pepe',
    address: 'Anwani',
    trustedSupplier: 'Msambazaji Anayeaminika',
    autoOrder: 'Agizo la Kiotomatiki',
    enableAutoOrder: 'Washa Agizo la Kiotomatiki',
    
    // Orders
    purchaseOrders: 'Maagizo ya Ununuzi',
    createOrder: 'Unda Agizo',
    orderStatus: 'Hali ya Agizo',
    pending: 'Inasubiri',
    ordered: 'Imeagizwa',
    received: 'Imepokelewa',
    cancelled: 'Imefutwa',
    autoGenerated: 'Imeundwa Kiotomatiki',
    confirmOrder: 'Thibitisha Agizo',
    markReceived: 'Weka Imepokelewa',
    cancelOrder: 'Futa Agizo',
    
    // Reports
    salesReport: 'Ripoti ya Mauzo',
    inventoryReport: 'Ripoti ya Bidhaa',
    expiryReport: 'Ripoti ya Kuisha',
    exportReport: 'Hamisha Ripoti',
    dateRange: 'Kipindi cha Tarehe',
    from: 'Kuanzia',
    to: 'Hadi',
    generateReport: 'Tengeneza Ripoti',
    
    // Settings
    language: 'Lugha',
    english: 'Kiingereza',
    swahili: 'Kiswahili',
    notifications: 'Arifa',
    lowStockThreshold: 'Kiwango cha Bidhaa Chache',
    expiryWarningDays: 'Siku za Onyo la Kuisha',
    saveSettings: 'Hifadhi Mipangilio',
    backupData: 'Hifadhi Nakala',
    restoreData: 'Rejesha Data',
    
    // Auth
    login: 'Ingia',
    username: 'Jina la Mtumiaji',
    password: 'Neno la Siri',
    loginError: 'Jina au neno la siri si sahihi',
    sessionExpired: 'Kipindi kimeisha. Tafadhali ingia tena.',
    
    // Common
    save: 'Hifadhi',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    view: 'Tazama',
    search: 'Tafuta',
    filter: 'Chuja',
    noResults: 'Hakuna matokeo',
    loading: 'Inapakia...',
    success: 'Imefanikiwa',
    error: 'Hitilafu',
    warning: 'Onyo',
    confirm: 'Thibitisha',
    actions: 'Vitendo',
    status: 'Hali',
    date: 'Tarehe',
    amount: 'Kiasi',
    price: 'Bei',
    unit: 'Kipimo',
    items: 'bidhaa',
    ksh: 'KSh',
    
    // Welcome
    welcomeBack: 'Karibu tena',
    agrovetSystem: 'Mfumo wa Usimamizi wa Agrovet',
  },
} as const;

export const getTranslation = (lang: Language, key: TranslationKey): string => {
  return translations[lang][key] || key;
};
