import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { suppliersApi, SupplierPayload } from '@/api/suppliers';
import { salesApi, CreateSalePayload } from '@/api/sales';
import { ordersApi, notificationsApi } from '@/api/orders';
import { toast } from 'sonner';

// ── Suppliers ─────────────────────────────────────────────────────────────────

export const SUPPLIERS_KEY = 'suppliers';

export const useSuppliers = (params?: { search?: string; limit?: number }) =>
  useQuery({
    queryKey: [SUPPLIERS_KEY, params],
    queryFn: () => suppliersApi.getAll(params),
    staleTime: 60_000,
  });

export const useCreateSupplier = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: SupplierPayload) => suppliersApi.create(payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [SUPPLIERS_KEY] });
      toast.success('Supplier added successfully');
    },
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to add supplier'),
  });
};

export const useUpdateSupplier = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, payload }: { id: string; payload: Partial<SupplierPayload> }) =>
      suppliersApi.update(id, payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [SUPPLIERS_KEY] });
      toast.success('Supplier updated');
    },
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to update supplier'),
  });
};

export const useDeleteSupplier = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => suppliersApi.delete(id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [SUPPLIERS_KEY] });
      toast.success('Supplier deleted');
    },
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to delete supplier'),
  });
};

// ── Sales ─────────────────────────────────────────────────────────────────────

export const SALES_KEY = 'sales';

export const useSales = (params?: { page?: number; limit?: number; startDate?: string; endDate?: string }) =>
  useQuery({
    queryKey: [SALES_KEY, params],
    queryFn: () => salesApi.getAll(params),
    staleTime: 30_000,
  });

export const useSalesSummary = (period: 'today' | 'week' | 'month' | 'year' = 'week') =>
  useQuery({
    queryKey: [SALES_KEY, 'summary', period],
    queryFn: () => salesApi.getSummary(period),
    staleTime: 60_000,
  });

export const useTopProducts = (limit = 10, period = 'month') =>
  useQuery({
    queryKey: [SALES_KEY, 'top-products', limit, period],
    queryFn: () => salesApi.getTopProducts(limit, period),
    staleTime: 60_000,
  });

export const useCreateSale = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: CreateSalePayload) => salesApi.create(payload),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [SALES_KEY] });
      qc.invalidateQueries({ queryKey: ['products'] });
    },
    onError: (err: any) => {
      // Show the exact server error so the user knows what went wrong
      const serverMsg = err.response?.data?.message;
      const validationErrors = err.response?.data?.errors;
      if (validationErrors?.length) {
        toast.error(`Validation: ${validationErrors.map((e: any) => e.message).join(', ')}`);
      } else {
        toast.error(serverMsg || 'Payment failed — check your connection and try again');
      }
    },
  });
};

export const useTransactionStatus = (checkoutRequestId: string | null, enabled: boolean) =>
  useQuery({
    queryKey: ['mpesa-transaction', checkoutRequestId],
    queryFn: () => salesApi.getTransactionStatus(checkoutRequestId!),
    enabled: !!checkoutRequestId && enabled,
    refetchInterval: (query) => {
      if (!checkoutRequestId || !enabled) return false;
      const status = query.state.data?.transaction?.status;
      if (!status || status === 'pending') return 5000;
      return false;
    },
    refetchIntervalInBackground: true,
    refetchOnWindowFocus: false,
    staleTime: 0,
    retry: false,
  });

// ── Orders ────────────────────────────────────────────────────────────────────

export const ORDERS_KEY = 'orders';

export const useOrders = (params?: { status?: string; isAutoGenerated?: boolean; limit?: number }) =>
  useQuery({
    queryKey: [ORDERS_KEY, params],
    queryFn: () => ordersApi.getAll(params),
    staleTime: 30_000,
  });

export const useUpdateOrderStatus = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, status }: { id: string; status: 'pending' | 'ordered' | 'received' | 'cancelled' }) =>
      ordersApi.updateStatus(id, status),
    onSuccess: (_, { status }) => {
      qc.invalidateQueries({ queryKey: [ORDERS_KEY] });
      if (status === 'received') qc.invalidateQueries({ queryKey: ['products'] });
      toast.success(`Order status updated to '${status}'`);
    },
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to update order'),
  });
};

export const useTriggerAutoCheck = () => {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ordersApi.triggerAutoCheck,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [ORDERS_KEY] });
      toast.success('Auto-order check triggered');
    },
  });
};

// ── Notifications ─────────────────────────────────────────────────────────────

export const NOTIFICATIONS_KEY = 'notifications';

export const useAlerts = () =>
  useQuery({
    queryKey: [NOTIFICATIONS_KEY, 'alerts'],
    queryFn: notificationsApi.getAlerts,
    staleTime: 60_000,
    refetchInterval: 5 * 60_000,
  });

export const useSendLowStockEmail = () =>
  useMutation({
    mutationFn: notificationsApi.sendLowStockEmail,
    onSuccess: () => toast.success('Low stock alert email sent'),
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to send email'),
  });

export const useSendExpiryEmail = () =>
  useMutation({
    mutationFn: notificationsApi.sendExpiryEmail,
    onSuccess: () => toast.success('Expiry alert email sent'),
    onError: (err: any) => toast.error(err.response?.data?.message || 'Failed to send email'),
  });
