// Product interface for inventory items
export interface Product {
  id: string;
  name: string;
  nameSwahili: string;
  category: ProductCategory;
  sku: string;
  quantity: number;
  minStockLevel: number;
  buyingPrice: number;
  sellingPrice: number;
  expiryDate: string | null;
  batchNumber: string;
  supplierId: string;
  createdAt: string;
  updatedAt: string;
}

// Product categories
export type ProductCategory = 
  | 'seeds' 
  | 'fertilizers' 
  | 'pesticides' 
  | 'veterinary' 
  | 'tools';

// Supplier interface
export interface Supplier {
  id: string;
  name: string;
  phone: string;
  email: string;
  address: string;
  products: string[]; // Product IDs
  isTrusted: boolean;
  autoOrderEnabled: boolean;
  createdAt: string;
  updatedAt: string;
}

// Cart item for POS
export interface CartItem {
  productId: string;
  name: string;
  nameSwahili: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

// Payment method types
export type PaymentMethod = 'cash' | 'mpesa';

// Sale record
export interface Sale {
  id: string;
  items: CartItem[];
  subtotal: number;
  total: number;
  paymentMethod: PaymentMethod;
  mpesaRef?: string;
  customerPhone?: string;
  createdAt: string;
}

// Order item for purchase orders
export interface OrderItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
}

// Purchase order status
export type OrderStatus = 'pending' | 'ordered' | 'received' | 'cancelled';

// Purchase order
export interface PurchaseOrder {
  id: string;
  supplierId: string;
  supplierName: string;
  items: OrderItem[];
  totalAmount: number;
  status: OrderStatus;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// App settings
export interface AppSettings {
  language: 'en' | 'sw';
  lowStockThreshold: number;
  expiryWarningDays: number;
  autoOrderEnabled: boolean;
}

// Admin session
export interface AdminSession {
  isAuthenticated: boolean;
  username: string;
  loginTime: string;
  expiresAt: string;
}

// Dashboard stats
export interface DashboardStats {
  totalProducts: number;
  lowStockItems: number;
  expiringItems: number;
  todaySales: number;
  todayRevenue: number;
}

// Notification type
export interface AppNotification {
  id: string;
  type: 'low_stock' | 'expiry_warning' | 'auto_order' | 'info';
  title: string;
  message: string;
  productId?: string;
  isRead: boolean;
  createdAt: string;
}
