import api from './client';

export interface OrderItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: number;
}

export interface PurchaseOrder {
  _id: string;
  supplierId: string | { _id: string; name: string; phone: string; email?: string };
  supplierName: string;
  items: OrderItem[];
  totalAmount: number;
  status: 'pending' | 'ordered' | 'received' | 'cancelled';
  isAutoGenerated: boolean;
  notes?: string;
  emailSent: boolean;
  orderedAt?: string;
  receivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export const ordersApi = {
  getAll: async (params?: {
    page?: number;
    limit?: number;
    status?: string;
    supplierId?: string;
    isAutoGenerated?: boolean;
  }) => {
    const { data } = await api.get('/orders', { params });
    return { data: data.data as PurchaseOrder[], pagination: data.pagination };
  },

  getById: async (id: string): Promise<PurchaseOrder> => {
    const { data } = await api.get(`/orders/${id}`);
    return data.data;
  },

  create: async (payload: {
    supplierId: string;
    items: { productId: string; quantity: number; unitPrice?: number }[];
    notes?: string;
  }): Promise<PurchaseOrder> => {
    const { data } = await api.post('/orders', payload);
    return data.data;
  },

  updateStatus: async (
    id: string,
    status: 'pending' | 'ordered' | 'received' | 'cancelled'
  ): Promise<PurchaseOrder> => {
    const { data } = await api.patch(`/orders/${id}/status`, { status });
    return data.data;
  },

  delete: async (id: string): Promise<void> => {
    await api.delete(`/orders/${id}`);
  },

  triggerAutoCheck: async (): Promise<void> => {
    await api.post('/orders/trigger-auto-check');
  },
};

// ── Notifications ─────────────────────────────────────────────────────────────

export interface AlertData {
  lowStock: { count: number; items: any[] };
  expiring: { count: number; items: any[] };
  expired: { count: number; items: any[] };
  totalAlerts: number;
}

export const notificationsApi = {
  getAlerts: async (): Promise<AlertData> => {
    const { data } = await api.get('/notifications/alerts');
    return data.data;
  },

  sendLowStockEmail: async () => {
    const { data } = await api.post('/notifications/send-low-stock');
    return data;
  },

  sendExpiryEmail: async () => {
    const { data } = await api.post('/notifications/send-expiry');
    return data;
  },

  runScheduler: async () => {
    const { data } = await api.post('/notifications/run-scheduler');
    return data;
  },
};